sudo: required

language: node_js

matrix:
  include:
    - language: python
      python: 2.7.10

node_js:
  - "9"

branches:
  only:
    - develop
    - master
    - "pre-release"

script: . test.sh
